//  SetCoolingCommand.java
// $Id$
package ngat.loci.ccd;

import java.io.*;
import java.lang.*;
import java.net.*;

import org.json.*;

import ngat.flask.EndPoint;
import ngat.util.logging.*;
import ngat.loci.ccd.Command;

/**
 * Invoke the Loci CCD Flask end-point 'setCooling'.
 * @author Chris Mottram
 * @version $Revision$
 */
public class SetCoolingCommand extends Command implements Runnable
{
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");
	/**
	 * Constant defining the log level to send for error messages generated by instances of this class.
	 */
	public final static int LOG_LEVEL_ERROR = 1;
	
	/**
	 * Default constructor. Call's the Command super-class constructor.
	 * Then sets the Flask end-point name to "setCooling" and the end-point to a "POST" end-point.
	 * @see #logger
	 * @see #endPoint
	 * @see ngat.flask.EndPoint#setFlaskEndPointName
	 * @see ngat.flask.EndPoint#setDoPost
	 */
	public SetCoolingCommand()
	{
		super();
		logger = LogManager.getLogger(this);
		endPoint.setFlaskEndPointName("setCooling");
		endPoint.setDoPost();
	}

	/**
	 * Set whether to turn the CCD cooling on or off in the CCD Flask endpoint.
	 * @param cooling A boolean, true to turn cooling on, and false to turn cooling off.
	 * @see #endPoint
	 * @see ngat.flask.EndPoint#addParameter(java.lang.String,boolean)
	 */
	public void setCooling(boolean cooling)
	{
		logger.log(Logging.VERBOSITY_VERBOSE,this.getClass().getName()+
			   ":setCooling:Set cooling to:"+cooling);
		endPoint.addParameter("cooling",cooling);
	}
	
	/**
	 * Return the message string returned by the Flask end-point.
	 * @return The message as a string returned by the Flask end-point 
	 *         (with the JSON key 'message').
	 * @see #endPoint
	 * @exception JSONException Thrown if the key is not found or if the value is not a string.
	 */
	public String getMessage() throws org.json.JSONException
	{
		return endPoint.getReturnValueString("message");
	}
	
	/**
	 * Main test program.
	 * @param args The argument list.
	 */
	public static void main(String args[])
	{
		SetCoolingCommand command = null;
		String hostname = null;
		boolean cooling;
		int portNumber = 5100;

		if(args.length != 3)
		{
			System.out.println("java ngat.loci.ccd.SetCoolingCommand <hostname> <port number> <cooling:true=on,false=off>");
			System.exit(1);
		}
		try
		{
			hostname = args[0];
			portNumber = Integer.parseInt(args[1]);
			cooling = Boolean.parseBoolean(args[2]);
			command = new SetCoolingCommand();
			command.initialiseLogging();
			command.setAddress(hostname);
			command.setPortNumber(portNumber);
			command.setCooling(cooling);
			command.run();
			if(command.getRunException() != null)
			{
				System.err.println("SetCoolingCommand: Command failed.");
				command.getRunException().printStackTrace(System.err);
				System.exit(1);
			}
			System.out.println("Finished:"+command.getCommandFinished());
			System.out.println("Http Response Code (200 on success):"+command.getHttpResponseCode());
			System.out.println("Return Status:"+command.getReturnStatus());
			System.out.println("Is Return Status Success:"+command.isReturnStatusSuccess());
			System.out.println("Message:"+command.getMessage());
		}
		catch(Exception e)
		{
			e.printStackTrace(System.err);
			System.exit(1);
		}
		System.exit(0);
	}
}
