// SetTemperatureCommand.java
package ngat.loci.ccd;

import java.io.*;
import java.lang.*;
import java.net.*;

import org.json.*;

import ngat.flask.EndPoint;
import ngat.util.logging.*;
import ngat.loci.ccd.Command;

/**
 * Invoke the Loci CCD Flask end-point 'setTemperature'.
 * @author Chris Mottram
 * @version $Revision$
 */
public class SetTemperatureCommand extends Command implements Runnable
{
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");
	/**
	 * Constant defining the log level to send for error messages generated by instances of this class.
	 */
	public final static int LOG_LEVEL_ERROR = 1;
	
	/**
	 * Default constructor. Call's the Command super-class constructor.
	 * Then sets the Flask end-point name to "setTemperature" and the end-point to a "POST" end-point.
	 * @see #logger
	 * @see #endPoint
	 * @see ngat.flask.EndPoint#setFlaskEndPointName
	 * @see ngat.flask.EndPoint#setDoPost
	 */
	public SetTemperatureCommand()
	{
		super();
		logger = LogManager.getLogger(this);
		endPoint.setFlaskEndPointName("setTemperature");
		endPoint.setDoPost();
	}

	/**
	 * Set the temperature passed to the Flask setTemperature end-point. This is the target temperature
	 * we want the CCD to attain in degrees centigrade.
	 * @param targetTemperature An integer, the target CCD temperature in degrees centigrade.
	 * @see #endPoint
	 * @see ngat.flask.EndPoint#addParameter(java.lang.String,int)
	 */
	public void setTemperature(int targetTemperature)
	{
		logger.log(Logging.VERBOSITY_VERBOSE,this.getClass().getName()+
			   ":setTemperature:Set target temperature to:"+targetTemperature);
		endPoint.addParameter("temperature",targetTemperature);
	}
	
	/**
	 * Return the message string returned by the Flask end-point.
	 * @return The message as a string returned by the Flask end-point 
	 *         (with the JSON key 'message').
	 * @see #endPoint
	 * @exception JSONException Thrown if the key is not found or if the value is not a string.
	 */
	public String getMessage() throws org.json.JSONException
	{
		return endPoint.getReturnValueString("message");
	}
	
	/**
	 * Main test program.
	 * @param args The argument list.
	 */
	public static void main(String args[])
	{
		SetTemperatureCommand command = null;
		String hostname = null;
		int targetTemperature;
		int portNumber = 5100;

		if(args.length != 3)
		{
			System.out.println("java ngat.loci.ccd.SetTemperatureCommand <hostname> <port number> <target temperature>");
			System.exit(1);
		}
		try
		{
			hostname = args[0];
			portNumber = Integer.parseInt(args[1]);
			targetTemperature = Integer.parseInt(args[2]);
			command = new SetTemperatureCommand();
			command.initialiseLogging();
			command.setAddress(hostname);
			command.setPortNumber(portNumber);
			command.setTemperature(targetTemperature);
			command.run();
			if(command.getRunException() != null)
			{
				System.err.println("SetTemperatureCommand: Command failed.");
				command.getRunException().printStackTrace(System.err);
				System.exit(1);
			}
			System.out.println("Finished:"+command.getCommandFinished());
			System.out.println("Http Response Code (200 on success):"+command.getHttpResponseCode());
			System.out.println("Return Status:"+command.getReturnStatus());
			System.out.println("Is Return Status Success:"+command.isReturnStatusSuccess());
			System.out.println("Message:"+command.getMessage());
		}
		catch(Exception e)
		{
			e.printStackTrace(System.err);
			System.exit(1);
		}
		System.exit(0);
	}
}
