// TakeBiasFrameCommand.java
package ngat.loci.ccd;

import java.io.*;
import java.lang.*;
import java.net.*;

import org.json.*;

import ngat.flask.EndPoint;
import ngat.util.logging.*;
import ngat.loci.ccd.Command;

/**
 * Invoke the Loci CCD Flask end-point 'takeBiasFrame'.
 * @author Chris Mottram
 * @version $Revision$
 */
public class TakeBiasFrameCommand extends Command implements Runnable
{
	/**
	 * Revision Control System id string, showing the version of the Class.
	 */
	public final static String RCSID = new String("$Id$");
	/**
	 * Constant defining the log level to send for error messages generated by instances of this class.
	 */
	public final static int LOG_LEVEL_ERROR = 1;
	
	/**
	 * Default constructor. Call's the Command super-class constructor.
	 * Then sets the Flask end-point name to "takeBiasFrame" and the end-point to a "POST" end-point.
	 * @see #logger
	 * @see #endPoint
	 * @see ngat.flask.EndPoint#setFlaskEndPointName
	 * @see ngat.flask.EndPoint#setDoPost
	 */
	public TakeBiasFrameCommand()
	{
		super();
		logger = LogManager.getLogger(this);
		endPoint.setFlaskEndPointName("takeBiasFrame");
		endPoint.setDoPost();
	}

	/**
	 * Set the filename passed to the Flask takeBiasFrame end-point. This is the FITS filename to put the read out
	 * bias frame image into.
	 * @param filename A string, the FITS filename.
	 * @see #endPoint
	 * @see ngat.flask.EndPoint#addParameter(java.lang.String,java.lang.String)
	 */
	public void setFilename(String filename)
	{
		endPoint.addParameter("filename",filename);
	}
	
	/**
	 * Return the message string returned by the Flask end-point.
	 * @return The message as a string returned by the Flask end-point 
	 *         (with the JSON key 'message').
	 * @see #endPoint
	 * @exception JSONException Thrown if the key is not found or if the value is not a string.
	 */
	public String getMessage() throws org.json.JSONException
	{
		return endPoint.getReturnValueString("message");
	}
	
	/**
	 * Main test program.
	 * @param args The argument list.
	 */
	public static void main(String args[])
	{
		TakeBiasFrameCommand command = null;
		String hostname = null;
		String filename = null;;
		int portNumber = 5100;

		if(args.length != 3)
		{
			System.out.println("java ngat.loci.ccd.TakeBiasFrameCommand <hostname> <port number> <filename>");
			System.exit(1);
		}
		try
		{
			hostname = args[0];
			portNumber = Integer.parseInt(args[1]);
			filename = args[2];
			command = new TakeBiasFrameCommand();
			command.initialiseLogging();
			command.setAddress(hostname);
			command.setPortNumber(portNumber);
			command.setFilename(filename);
			command.run();
			if(command.getRunException() != null)
			{
				System.err.println("TakeBiasFrameCommand: Command failed.");
				command.getRunException().printStackTrace(System.err);
				System.exit(1);
			}
			System.out.println("Finished:"+command.getCommandFinished());
			System.out.println("Return Status:"+command.getReturnStatus());
			System.out.println("Is Return Status Success:"+command.isReturnStatusSuccess());
			System.out.println("Message:"+command.getMessage());
		}
		catch(Exception e)
		{
			e.printStackTrace(System.err);
			System.exit(1);
		}
		System.exit(0);
	}
}
